### Site info:
title: Ankush Sharma's Blog
tagline: Web Dev for the sane.
author: Ankush Sharma
email: ankush20058@gmail.com
description: "Web Development for the Sane." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
locale: en_US

### Personal info and site tools info:
github_username:  Ankush1992
disqus_shortname: ankush1992
favicon:     "/images/favicon.ico"
aboutme: Do not like short about me's.
aboutme_photo: https://cloud.githubusercontent.com/assets/7692552/10868650/1c68b6e8-80ba-11e5-9f1d-ba63205075fd.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
