name: Ankush Sharma
# markdown: redcarpet
# pygments: true
github: https://github.com/ankushs92
about: Software dev from Delhi, India. Interested in high performance web applications. Learning ML!
urls:
    - text: github
      url: https://github.com/ankushs92
      icon: <i class="fa fa-github fa-2x" aria-hidden="true"></i>
    - text: email
      url: mailto:ankush20058@gmail.com
      icon: <i class="fa fa-envelope fa-2x" aria-hidden="true"></i>
    - text: linkedin
      url: https://www.linkedin.com/in/ankushs92/
      icon: <i class="fa fa-linkedin fa-2x" aria-hidden="true"></i>
    - text: goodreads
      url: https://www.goodreads.com/ankushsharma
      icon: <i class="fa fa-book fa-2x" aria-hidden="true"></i>
      
